### ISSUE TITLE
wrong coding method

### ISSUE THREAD

**Issue by erfanzar** [infotrex/bulk-upload-to-opensea#234] opened 2022-07-13 09:50 UTC
hello 
to be honest i dont mean to be rude and i dont want to be but at least you could code a bit cleaner or better how can you have 3 errors in somthing published on github

**Comment by karakule3dfx** [comment] 2022-07-15 06:26
@erfanzar 

my english is not very good. so I don't understand exactly what you mean when you say 3 errors. I'm not the owner of the project, I added the things I need while using it. I am not knowledgeable about python, I just studied python in this project. I'm not a pro at writing code. I'm just trying to help as much as I can. I have no income from this project. I corrected the problems I had while using the program so that others would not experience it, and transferred them here. If you tell me exactly what the problem is, I will try to fix it and improve myself. 

Could you help me?

**Closed as completed** 2022-07-21 05:57 UTC
